name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check Yarn Version
        run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build
        run: |
          yarn build
